from locators.header_locators import HeaderLocators
from locators.favourite_locators import FavouriteLocators
from locators.login_locators import LogoLocators
from locators.main_locators import MainLocators
